journalClubDB/journalClubDB/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^papers/', include('papers.urls', namespace="papers")),

    # for description of django.contrib.auth.urls, see: https://docs.djangoproject.com/en/1.8/topics/auth/default/#using-the-views for description of django.contrib.auth.urls
    url('^', include('django.contrib.auth.urls')),

    # See https://realpython.com/blog/python/adding-social-authentication-to-django/
    url('', include('social.apps.django_app.urls', namespace='social')),



]

journalClubDB/papers/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    # ex: /papers/
    url(r'^$', views.frontpage, name='frontpage'),

    # about pages
    url(r'^about_contact/$', views.about_contact, name='about_contact'),

    url(r'^about_developers/$', views.about_developers, name='about_developers'),
    url(r'^about_jcdb/$', views.about_jcdb, name='about_jcdb'),


    # ex: /paperOfTheWeek_list/
    url(r'^paperOfTheWeek_list/$', views.paperOfTheWeek_list, name='paperOfTheWeek_list'),

    # ex: /papers/index/
    url(r'^index/$', views.index, name='index'),

    # ex: /papers/self_user_profile/
    url(r'^self_user_profile/$', views.self_user_profile, name='self_user_profile'),

    # ex: /papers/self_user_profile/
    url(r'^add_citation_to_user_library/$', views.add_citation_to_user_library, name='add_citation_to_user_library'),


    url(r'^user_notifications/$', views.user_notifications, name='user_notifications'),

    url(r'^user_library/$', views.user_library, name='user_library'),

    # ex:
    url(r'^post_context/(?P<post_pk>[0-9]+)/$', views.post_context, name='post_context'),
    url(r'^post_single/(?P<post_pk>[0-9]+)/$', views.post_single, name='post_single'),

    # ex:
    url(r'^user_posts/(?P<user_pk>[0-9]+)/$', views.user_posts, name='user_posts'),

    # ex: /papers/search/0/
    url(r'^search/(?P<page>[0-9]+)/$', views.search, name='search'),

    # ex: /papers/addCitation/
    url(r'^addCitation/$', views.addCitation, name='addCitation'),

    # ex:
    url(r'^deletePost/$', views.deletePost, name='deletePost'),
    url(r'^addPost/$', views.addPost, name='addPost'),
    url(r'^editPersonalNote/$', views.editPersonalNote, name='editPersonalNote'),
    url(r'^postForm/$', views.postForm, name='postForm'),
    url(r'^personalNoteForm/$', views.personalNoteForm, name='personalNoteForm'),


    # ex:
    url(r'^upvote/$', views.upvote, name='upvote'),

    # ex:
    url(r'^downvote/$', views.downvote, name='downvote'),


    # ex: /papers/detail/0/0/
    url(r'^detail/(?P<pk>[0-9]+)/(?P<current_thread>[0-9]+)/$', views.detail, name='detail'),

    url(r'^register/$', views.register, name='register'), # ADD NEW PATTERN!
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^user_logout/$', views.user_logout, name='user_logout'),
    url(r'^add_tag/$', views.add_tag, name='add_tag'),

    url(r'^paperOfTheWeek_admin/$', views.paperOfTheWeek_admin, name='paperOfTheWeek_admin'),


]

journalClubDB/templates/base-navbar.html
<!-- navbar at the top of the page -->
<!-- this should be included in base.html -->
{% load templatetags %}
{% load staticfiles %}
<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'bootstrap-3.3.5-dist/js/bootstrap.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/base-navbar.css' %}">


  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href=".">journalClubDB<sup class="color-green">BETA</sup></a>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <div class="span2"></div>
          <!-- home button -->
          <li class="{% if navbar == 'home' %}active{% endif %}"><a href="{% url 'papers:frontpage' %}">Home</a></li>

          <!-- search button -->
          <li class="dropdown {% if navbar == 'search' %}active{% endif %}">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Search<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'papers:index' %}">Search JCDB</a></li>
              {% if user.is_authenticated %}
                <li><a href="{% url 'papers:search' 0 %}">Import papers from pubmed</a></li>
              {% else %}
                <li>
                  <a data-toggle="modal" data-target="#social-auth-modal" class="pointer activate-login-modal-import">
                    Import papers from pubmed
                  </a>
                </li>
              {% endif %}
            </ul>
          </li>
          <li class="dropdown {% if navbar == 'about' %}active{% endif %}">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'papers:about_jcdb' %}">Tell me about this website!</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'papers:about_developers' %}">About the developers</a></li>
            </ul>
          </li>
        </ul>
        <!-- navbar (right side)-->
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li class="dropdown {% if navbar == 'user_profile' %}active{% endif %}">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.get_username }}
                                                                                                                                  {% if user|reply_notifications|length != 0 %}
                                                                                                                                    <span class="bold-red">({{ user|reply_notifications|length }})</span>
                                                                                                                                  {% endif %}
                                                                                                                                  {% if number_of_post_reply_notifications %}
                                                                                                                                    <span class="bold-red">({{ number_of_post_reply_notifications }})</span>
                                                                                                                                  {% endif %}
                                                                                                                                  <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'papers:self_user_profile' %}">User Profile</a></li>
                <li><a href="{% url 'papers:user_posts' user.pk %}">Your Posts</a></li>
                <li><a href="{% url 'papers:user_library' %}">Your Library</a></li>
                <li><a href="{% url 'papers:user_notifications' %}">Notifications
                                                                    {% if user|reply_notifications|length != 0 %}
                                                                      <span class="bold-red">({{ user|reply_notifications|length }})</span>
                                                                    {% endif %}
                                                                    {% if number_of_post_reply_notifications %}
                                                                      <span class="bold-red">({{ number_of_post_reply_notifications }})</span>
                                                                    {% endif %}
                    </a>
                </li>
                <li role="separator" class="divider"></li>
                <li><a id="logout_button" href="{% url 'papers:user_logout' %}">Logout</a></li>
              </ul>
            </li>
          {% else %}
              <li class="active pointer"><a class="activate-login-modal-navbar" data-toggle="modal" data-target="#social-auth-modal">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

journalClubDB/templates/citation_summary_template.html
<!-- this template contains html to display a single citation -->
<!-- requires template variable: citation -->
{% load templatetags %}
<div>
  {% if is_search_results %}
    <a id="citation-toggle-{{ forloop.counter }}" class="list-group-item pointer" data-toggle="collapse" data-target="#citation-item-{{ forloop.counter }}" data-parent="#menu"> <!-- TODO: color this (active?) -->
  {% else %}
    <a id="citation-toggle-{{ citation.pk }}" class="list-group-item pointer" data-toggle="collapse" data-target="#citation-item-{{ citation.pk }}" data-parent="#menu"> <!-- TODO: color this (active?) -->
  {% endif %}
    <h4 class="list-group-item-heading">{{ citation.title }}</h4>
    <p class="list-group-item-text">{{ citation.get_author_list_truncated }} ({{ citation.get_year_published }}). {{ citation.get_journal }}.</p>
  </a>

  {% if is_search_results %}
    <div id="citation-item-{{ forloop.counter }}" class="citation-index-all sublinks collapse {% if forloop.counter == 1 %}in{% endif %}"> <!-- start with first entry not collapsed -->
  {% else %}
    <div id="citation-item-{{ citation.pk }}" class="citation-index-all sublinks collapse {% if forloop.counter == 1 %}in{% endif %}"> <!-- start with first entry not collapsed -->
  {% endif %}
    <a class="list-group-item small">{{ citation.abstract }}</a>

    {% if is_search_results %}
      {% if citation.preExistingEntryExists != -1 %}
        <a class="list-group-item" href="{% url 'papers:detail' citation.preExistingEntryExists  0 %}">
          <button type="button" class="btn btn-primary btn-xs">Discuss in JCDB</button>
        </a>
      {% else %} <!-- functionality to import citations into JCDB. Submission handled by javascript in search.js -->
        <a class="list-group-item">
          <button type="button" class="btn btn-primary btn-xs import-button">Import to JCDB</button>
          <form action="{% url 'papers:addCitation' %}" method=POST class="inline">
            {% csrf_token %}
            <input type="hidden" name="citation_serialized" value="{{ citation.serialize }}" />
          </form>
        </a>
      {% endif %}
    {% else %}
      {% if citation.tags.all|length != 0 %}
        <a class="list-group-item small">Tags:
        {% for tag in citation.tags.all %}
          <span class="label label-primary">{{ tag }}</span>
        {% endfor %}
        </a>
      {% endif %}
      <a class="list-group-item" href="{% url 'papers:detail' citation.pk  0 %}">
        <button type="button" class="btn btn-primary btn-xs">Click to discuss this paper!</button>
      </a>
    {% endif %}

  </div>
</div>

journalClubDB/templates/post_template.html
<!-- this template contains html to display a user post -->
{% load templatetags %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/post_template.css' %}">
<script src="{% static "/static/js/post_template.js" %}"></script>
<script>
  csrf_js = '{{ csrf_token }}'
  url_upvote = "{% url 'papers:upvote' %}"
  url_downvote = "{% url 'papers:downvote' %}"
</script>

<div id="post-{{ p.pk }}" class="post-wrapper">


<table>
<tbody>
<tr>

<!-- interface to vote up or down a comment -->
<!--
<td class="post-voting-interface">
  <div>
    {% if user.is_authenticated %}
      {% if p|post_upvoted_by_user:user.pk %}
        <input type="hidden" name="post_pk" value="{{ p.pk }}">
        <a id="up-{{ p.pk }}" class="upvoted-arrow" title="This answer is useful">up vote</a>
      {% else %}
        <input type="hidden" name="post_pk" value="{{ p.pk }}">
        <a id="up-{{ p.pk }}" class="up-arrow" title="This answer is useful">up vote</a>
      {% endif %}
    {% else %}
        <div class="active pointer" id="upvote-modal"><a id="up-{{ p.pk }}" class="up-arrow activate-login-modal-vote" data-toggle="modal" data-target="#social-auth-modal">up vote</a></div>
    {% endif %}


    {% if user.is_authenticated %}
      {% if p|post_downvoted_by_user:user.pk %}
        <input type="hidden" name="post_pk" value="{{ p.pk }}">
        <a id="down-{{ p.pk }}" class="downvoted-arrow" title="This answer is not useful">down vote</a>
      {% else %}
        <input type="hidden" name="post_pk" value="{{ p.pk }}">
        <a id="down-{{ p.pk }}" class="down-arrow" title="This answer is not useful">down vote</a>
      {% endif %}
    {% else %}
      <div class="active pointer" id="downvote-modal"><a id="down-{{ p.pk }}" class="down-arrow activate-login-modal-vote" data-toggle="modal" data-target="#social-auth-modal">down vote</a></div>
    {% endif %}
  </div>
</td>
-->

{% if False %}

  <div class="deleted">
    [[ this post was deleted ]]
  </div>

{% else %}

  <td class="answercell">
    <!-- top bar containing username, points, time posted -->
    <div class="post-top-box">
      {% if not p.deleted %}
        <span><a class="bold comment-user pointer" href="{% url 'papers:user_posts' p.creator.pk %}">{{ p.creator.username }}</a></span>
      {% else %}
        <span><a class="bold comment-user pointer">unknown user</a></span>
      {% endif %}
      <span>&nbsp;</span>

      {% if not p.deleted %}
        <span id="commentscore-pk-{{ p.pk }}" class="comment-score">{{ p.score }}</span><span class="comment-score"> point{{p.score|pluralize}}</span>
        <span class="comment-time" id="comment-time-{{ p.pk }}">
          {{ p.time_created|age }}
        </span>
      {% endif %}
    </div>

    <!-- middle box containing post content. javascript used to switch between edits -->
    <div class="post-middle-box">
      {% for recent_post in p.get_undecoded_textTupleVector %}
        <div id="comment-text-{{ p.pk }}-{{ forloop.counter }}" class="comment-text comment-target-all-{{ p.pk }} comment-all {% if forloop.last %} comment-last {% endif %}">
          {% if not p.deleted %}
            {{ recent_post.0 | safe}} <!-- text -->
          {% else %}
            <p>[[ this post was deleted ]]</p>
          {% endif %}
        </div>
      {% endfor %}
    </div>

    {% if not p.deleted %}

    <!-- bottom bar containing reply, edit history -->
      <div class="post-bottom-box">
        <!-- upvote button -->
        <span>
        {% if user.is_authenticated %}
            <input type="hidden" name="post_pk" value="{{ p.pk }}">
            {% if p|post_upvoted_by_user:user.pk %}
              <a id="up-{{ p.pk }}" class="upvoted-arrow pointer active-vote" title="This comment is useful">upvoted</a>
            {% else %}
              <a id="up-{{ p.pk }}" class="up-arrow pointer" title="This comment is useful">upvote</a>
            {% endif %}
        {% else %}
          <a class="activate-login-modal-vote pointer" data-toggle="modal" data-target="#social-auth-modal" title="This comment is useful">upvote</a>
        {% endif %}
        &nbsp;
        </span>

        <!-- downvote button -->
        <span>
        {% if user.is_authenticated %}
          <input type="hidden" name="post_pk" value="{{ p.pk }}">
          {% if p|post_downvoted_by_user:user.pk %}
            <a id="down-{{ p.pk }}" class="downvoted-arrow pointer active-vote" title="This comment not useful">downvoted</a>
          {% else %}
            <a id="down-{{ p.pk }}" class="down-arrow pointer" title="This comment not useful">downvote</a>
          {% endif %}
        {% else %}
          <a class="activate-login-modal-vote pointer" data-toggle="modal" data-target="#social-auth-modal" title="This comment is not useful">downvote</a>
        {% endif %}
        &nbsp;
        </span>

        {% if user.is_authenticated %}

          <!-- reply button -->
          <span>
            <a class='hyperlink-submit-form'>reply</a> &nbsp;
            <form class="inline" action="{% url 'papers:postForm' %}" method=POST>
              {% csrf_token %}
              <input type="hidden" name="citation" value="{{ p.thread.owner.title }}" />
              <input type="hidden" name="citation_pk" value="{{ p.thread.owner.pk }}" />
              <input type="hidden" name="thread_title" value="{{ p.thread.title }}" />
              <input type="hidden" name="thread_description" value="{{ p.thread.description }}" />
              <input type="hidden" name="thread_pk" value="{{ p.thread.pk }}" />
              <input type="hidden" name="isReplyToPost" value="1" />
              <input type="hidden" name="mother_pk" value="{{ p.pk }}" />
              <input type="hidden" name="initial_text" value="{% with p.get_undecoded_textTupleVector|last as recent_post %}
                                                                {{ recent_post.0 }}
                                                              {% endwith %}">
              <input type="hidden" name="blockquote" value="False" />
              <input type="hidden" name="post_pk" value="-1" />
              <input type="hidden" name="edit_or_reply" value="reply" />
            </form>
          </span>

          <!-- edit/delete only shown if user created post) -->
          {% if user.get_username == p.creator.username %}
            <!-- edit button -->
            <span>
              <a class='hyperlink-submit-form'>edit</a> &nbsp;
              <form class="inline" action="{% url 'papers:postForm' %}" method=POST>
                {% csrf_token %}
                <input type="hidden" name="citation" value="{{ p.thread.owner.title }}" />
                <input type="hidden" name="citation_pk" value="{{ p.thread.owner.pk }}" />
                <input type="hidden" name="thread_title" value="{{ p.thread.title }}" />
                <input type="hidden" name="thread_description" value="{{ p.thread.description }}" />
                <input type="hidden" name="thread_pk" value="{{ p.thread.pk }}" />
                <input type="hidden" name="isReplyToPost" value="1" />
                <input type="hidden" name="mother_pk" value="{{ p.pk }}" />
                <input type="hidden" name="initial_text" value="{% with p.get_undecoded_textTupleVector|last as recent_post %}
                                                                  {{ recent_post.0 }}
                                                                {% endwith %}
                                                                "/>
                <input type="hidden" name="blockquote" value="False" />
                <input type="hidden" name="post_pk" value="{{ p.pk }}" />
                <input type="hidden" name="edit_or_reply" value="edit" />
              </form>
            </span>

            <!-- delete button -->
            <a class='delete-post-button pointer'>delete</a>
            <div class='delete-post-are-you-sure color-red inline'>
              are you sure?
              <a class='delete-post-yes pointer'>yes</a>
              <form class="inline" action="{% url 'papers:deletePost' %}" method=POST>
                {% csrf_token %}
                <input type="hidden" name="post_pk" value="{{ p.pk }}" />
              </form>
              /
              <a class='delete-post-no pointer'>no</a>
            </div>
            <div class='delete-post-confirmation color-black inline'>deleted</div>
             &nbsp;
          </span>

          {% endif %}


        <!-- if user is not authenticated -->
        {% else %}
          <span>
            <span><a data-toggle="modal" data-target="#social-auth-modal" class="pointer activate-login-modal-post">reply</a>  &nbsp; </span>
          </span>

        {% endif %}
        <!-- dropdown to select post history -->
        <span>
          <span class="dropdown">
               <a data-toggle="dropdown" class="dropdown-toggle pointer">history <b class="caret"></b></a> &nbsp;
               <ul class="dropdown-menu">
                 {% for recent_post in p.get_undecoded_textTupleVector %}
                   <li class="pointer li-dropdown-{{p.pk}} li-dropdown-{{p.pk}}-{{forloop.counter}} {% if forloop.last %} active {% endif %}"><a id="action-{{ p.pk }}-{{ forloop.counter }}" >
                     {% if recent_post.3 != p.creator.username %}
                       recent_post.3
                     {% endif %}
                     {% if forloop.counter == 1 %}
                       posted
                     {% else %}
                       edited
                     {% endif %}
                     {{ recent_post.2|age }}
                   </a></li> <!-- time created/edited -->
                 {% endfor %}
               </ul>
           </span>
        </span>

        <span>
          <a href="{% url 'papers:post_context' p.pk %}">context</a>
        </span>

      </div>
    {% endif %}
  </td>

{% endif %}

</tr>
</tbody>
</table>

</div>

journalClubDB/templates/post_template_condensed.html
<!-- this template contains html to display a user post -->
{% load templatetags %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/post_template.css' %}">
<script src="{% static "/static/js/post_template_condensed.js" %}"></script>
<script>
  csrf_js = '{{ csrf_token }}'
  url_upvote = "{% url 'papers:upvote' %}"
  url_downvote = "{% url 'papers:downvote' %}"
</script>

<div id="post-{{ p.pk }}" class="post-wrapper">


<table>
  <tbody>
    <tr>




        <td class="answercell">
          <!-- box containing post content. javascript used to switch between edits -->
          <span class="post-middle-box">
            {% for recent_post in p.get_undecoded_textTupleVector %}
              <span id="comment-text-{{ p.pk }}-{{ forloop.counter }}" class="condensed-comment-text comment-text comment-target-all-{{ p.pk }} comment-all {% if forloop.last %} comment-last {% endif %}">
                {% if p.deleted %}
                  <p>[[ this post was deleted ]]</p>
                {% else %}
                  {{ recent_post.0 | safe}} <!-- text -->
                {% endif %}
              </span>
            {% endfor %}
          </span>

          <!-- username, points, time posted -->
          <span class="post-top-box-condensed">
            <span>&mdash;</span>
            {% if p.deleted %}
              <span><a class="bold comment-user pointer">unknown user</a></span>
            {% else %}
              <!-- dropdown to select post history -->
              {% if not p.deleted %}
                <span class="dropdown">
                  <a data-toggle="dropdown" class="dropdown-toggle pointer"><b class="comment-user">{{ p.creator.username }}</b></a> &nbsp;
                  <ul class="dropdown-menu">
                    <li>
                      <!-- score and time, no selection choice -->
                      <a>
                      <span id="commentscore-pk-{{ p.pk }}" class="comment-score">{{ p.score }}</span><span class="comment-score"> point{{p.score|pluralize}}</span>
                      <span class="comment-time" id="comment-time-{{ p.pk }}">
                        {{ p.time_created|age }}
                      </span>
                      </a>
                  </li>

                     <!-- upvote button -->
                     <li>
                        {% if user.is_authenticated %}
                        <input type="hidden" name="post_pk" value="{{ p.pk }}">
                          {% if p|post_upvoted_by_user:user.pk %}
                            <a id="up-{{ p.pk }}" class="upvoted-arrow pointer active-vote" title="This comment is useful">upvoted</a>
                            {% else %}
                            <a id="up-{{ p.pk }}" class="up-arrow pointer" title="This comment is useful">upvote</a>
                          {% endif %}
                        {% else %}
                          <a class="activate-login-modal-vote pointer" data-toggle="modal" data-target="#social-auth-modal" title="This comment is useful">upvote</a>
                        {% endif %}
                      </li>
                      <!-- downvote button -->
                      <li>
                        {% if user.is_authenticated %}
                          <input type="hidden" name="post_pk" value="{{ p.pk }}">
                          {% if p|post_downvoted_by_user:user.pk %}
                            <a id="down-{{ p.pk }}" class="downvoted-arrow pointer active-vote" title="This comment not useful">downvoted</a>
                          {% else %}
                            <a id="down-{{ p.pk }}" class="down-arrow pointer" title="This comment not useful">downvote</a>
                          {% endif %}
                        {% else %}
                          <a class="activate-login-modal-vote pointer" data-toggle="modal" data-target="#social-auth-modal" title="This comment is not useful">downvote</a>
                        {% endif %}
                      </li>
                      <li class="divider"></li>


                      <!-- reply button -->
                      <li>
                        {% if user.is_authenticated %}
                          <a class='hyperlink-submit-form inline'>reply</a>
                          <form class="inline" action="{% url 'papers:postForm' %}" style="display: none;" method=POST>
                            {% csrf_token %}
                            <input type="hidden" name="citation" value="{{ p.thread.owner.title }}" />
                            <input type="hidden" name="citation_pk" value="{{ p.thread.owner.pk }}" />
                            <input type="hidden" name="thread_title" value="{{ p.thread.title }}" />
                            <input type="hidden" name="thread_description" value="{{ p.thread.description }}" />
                            <input type="hidden" name="thread_pk" value="{{ p.thread.pk }}" />
                            <input type="hidden" name="isReplyToPost" value="1" />
                            <input type="hidden" name="mother_pk" value="{{ p.pk }}" />
                            <input type="hidden" name="initial_text" value="{% with p.get_undecoded_textTupleVector|last as recent_post %}
                                                                              {{ recent_post.0 }}
                                                                            {% endwith %}">
                            <input type="hidden" name="blockquote" value="False" />
                            <input type="hidden" name="post_pk" value="-1" />
                            <input type="hidden" name="edit_or_reply" value="reply" />
                          </form>
                        {% else %}
                          <a data-toggle="modal" data-target="#social-auth-modal" class="pointer activate-login-modal-post">reply</a>
                        {% endif %}
                      </li>

                      <!-- edit button (only shown if user created post) -->
                      {% if user.get_username == p.creator.username %}
                      <li>
                        <a class='hyperlink-submit-form'>edit</a>
                        <form class="inline" action="{% url 'papers:postForm' %}" style="display: none;" method=POST>
                          {% csrf_token %}
                          <input type="hidden" name="citation" value="{{ p.thread.owner.title }}" />
                          <input type="hidden" name="citation_pk" value="{{ p.thread.owner.pk }}" />
                          <input type="hidden" name="thread_title" value="{{ p.thread.title }}" />
                          <input type="hidden" name="thread_description" value="{{ p.thread.description }}" />
                          <input type="hidden" name="thread_pk" value="{{ p.thread.pk }}" />
                          <input type="hidden" name="isReplyToPost" value="1" />
                          <input type="hidden" name="mother_pk" value="{{ p.pk }}" />
                          <input type="hidden" name="initial_text" value="{% with p.get_undecoded_textTupleVector|last as recent_post %}
                                                                            {{ recent_post.0 }}
                                                                          {% endwith %}
                                                                          "/>
                          <input type="hidden" name="blockquote" value="False" />
                          <input type="hidden" name="post_pk" value="{{ p.pk }}" />
                          <input type="hidden" name="edit_or_reply" value="edit" />
                        </form>
                      </li>
                      {% endif %}

                      <!-- delete button (only shown if user created post) -->
                      {% if user.get_username == p.creator.username %}
                      <li>
                        <a class='delete-post-button pointer'>delete</a>
                        <div class='delete-post-are-you-sure color-red inline'>
                          &nbsp; are you sure?
                          <a class='delete-post-yes pointer'>yes</a>
                          <form class="inline" action="{% url 'papers:deletePost' %}" method=POST>
                            {% csrf_token %}
                            <input type="hidden" name="post_pk" value="{{ p.pk }}" />
                          </form>
                          /
                          <a class='delete-post-no pointer'>no</a>
                        </div>
                        <div class='delete-post-confirmation color-black inline'>deleted</div>
                      </li>
                      {% endif %}

                      <li class="divider"></li>
                      <!-- history -->
                      <li class="dropdown-submenu">
                        <a>history</a>
                        <ul class="dropdown-menu">
                          {% for recent_post in p.get_undecoded_textTupleVector %}
                            <li class="li-dropdown-{{p.pk}} li-dropdown-{{p.pk}}-{{forloop.counter}} {% if forloop.last %} active {% endif %}"><a id="action-{{ p.pk }}-{{ forloop.counter }}" class="pointer">
                              {% if recent_post.3 != p.creator.username %}
                                recent_post.3
                              {% endif %}
                              {% if forloop.counter == 1 %}
                                posted
                              {% else %}
                                edited
                              {% endif %}
                              {{ recent_post.2|age }}
                            </a></li> <!-- time created/edited -->
                          {% endfor %}
                        </ul>
                     </li>
                     <!-- context -->
                     <li>
                       <a href="{% url 'papers:post_context' p.pk %}">context</a>
                     </li>
                     <li class="divider"></li>
                     <!-- user profile -->
                     <li>
                       <a class="bold comment-user pointer" href="{% url 'papers:user_posts' p.creator.pk %}">See more posts by user</a>
                     </li>



                   </ul>
                 </span>
              {% endif %}
            {% endif %}
          </span>
        </td>


    </tr>
  </tbody>
</table>

</div>