journalClubDB/journalClubDB/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^papers/', include('papers.urls', namespace="papers")),

    # for description of django.contrib.auth.urls, see: https://docs.djangoproject.com/en/1.8/topics/auth/default/#using-the-views for description of django.contrib.auth.urls
    url('^', include('django.contrib.auth.urls')),

    # See https://realpython.com/blog/python/adding-social-authentication-to-django/
    url('', include('social.apps.django_app.urls', namespace='social')),



]

journalClubDB/papers/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    # ex: /papers/
    url(r'^$', views.frontpage, name='frontpage'),

    # about pages
    url(r'^about_contact/$', views.about_contact, name='about_contact'),

    url(r'^about_developers/$', views.about_developers, name='about_developers'),
    url(r'^about_jcdb/$', views.about_jcdb, name='about_jcdb'),


    # ex: /paperOfTheWeek_list/
    url(r'^paperOfTheWeek_list/$', views.paperOfTheWeek_list, name='paperOfTheWeek_list'),

    # ex: /papers/index/
    url(r'^index/$', views.index, name='index'),

    # ex: /papers/self_user_profile/
    url(r'^self_user_profile/$', views.self_user_profile, name='self_user_profile'),

    # ex: /papers/self_user_profile/
    url(r'^add_citation_to_user_library/$', views.add_citation_to_user_library, name='add_citation_to_user_library'),


    url(r'^user_notifications/$', views.user_notifications, name='user_notifications'),

    url(r'^user_library/$', views.user_library, name='user_library'),

    # ex:
    url(r'^post_context/(?P<post_pk>[0-9]+)/$', views.post_context, name='post_context'),
    url(r'^post_single/(?P<post_pk>[0-9]+)/$', views.post_single, name='post_single'),

    # ex:
    url(r'^user_posts/(?P<user_pk>[0-9]+)/$', views.user_posts, name='user_posts'),

    # ex: /papers/search/0/
    url(r'^search/(?P<page>[0-9]+)/$', views.search, name='search'),

    # ex: /papers/addCitation/
    url(r'^addCitation/$', views.addCitation, name='addCitation'),

    # ex:
    url(r'^deletePost/$', views.deletePost, name='deletePost'),
    url(r'^addPost/$', views.addPost, name='addPost'),
    url(r'^editPersonalNote/$', views.editPersonalNote, name='editPersonalNote'),
    url(r'^postForm/$', views.postForm, name='postForm'),
    url(r'^personalNoteForm/$', views.personalNoteForm, name='personalNoteForm'),


    # ex:
    url(r'^upvote/$', views.upvote, name='upvote'),

    # ex:
    url(r'^downvote/$', views.downvote, name='downvote'),


    # ex: /papers/detail/0/0/
    url(r'^detail/(?P<pk>[0-9]+)/(?P<current_thread>[0-9]+)/$', views.detail, name='detail'),

    url(r'^register/$', views.register, name='register'), # ADD NEW PATTERN!
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^user_logout/$', views.user_logout, name='user_logout'),
    url(r'^add_tag/$', views.add_tag, name='add_tag'),

    url(r'^paperOfTheWeek_admin/$', views.paperOfTheWeek_admin, name='paperOfTheWeek_admin'),


]

journalClubDB/papers/views.py
from django.shortcuts import render, redirect, render_to_response
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
import logging
import math
from .models import *
#from .forms import UserForm #, UserProfileForm
from .Pubmed import PubmedInterface
logger = logging.getLogger(__name__)
import time
import pickle # used to debug, remove later
import os
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
#from datetime import datetime, timedelta, timezone
import datetime
import json
import re


def add_indent_dedent_to_post_list(post_list):
    rn =  add_indent_dedent_to_post_list_recursive(post_list,0,0,[])
    return rn

def add_indent_dedent_to_post_list_recursive(post_list,i,position_post,rn):
    if i>=len(post_list):
        return rn
    elif i==0:
        post = post_list[i]
        rn = ['in-'+str(post.node_depth),post,'out-'+str(post.node_depth)] # note that position of post = 1
        position_post = 1
        return add_indent_dedent_to_post_list_recursive(post_list,i+1,position_post,rn)
    else:
        post = post_list[i]
        previous_post = post_list[i-1]
        insert = ['in-'+str(post.node_depth),post,'out-'+str(post.node_depth)]
        if post.node_depth == previous_post.node_depth:
            rn[position_post+2:position_post+2] = insert
            position_post = (position_post+2) + 1
        elif post.node_depth > previous_post.node_depth:
            rn[position_post+1:position_post+1] = insert
            position_post = (position_post+1) + 1
        elif post.node_depth < previous_post.node_depth:
            for j in range(position_post+2,len(post_list)):
                if post_list[j] == 'out-'+str(post.node_depth):
                    rn[j+1:j+1] = insert
                    position_post = (j+1) + 1
                    break
        return add_indent_dedent_to_post_list_recursive(post_list,i+1,position_post,rn)

# rn should start an empty list
def get_post_chain(post):
    rn = get_post_chain_recursive(post,[])
    return rn[::-1] # reverse list so that most recent post is at end of the list

# rn should start an empty list
def get_post_chain_recursive(post,rn):
    rn.append(post)
    mother = post.mother
    if mother.node_depth == 0:
        return rn
    else:
        return get_post_chain_recursive(mother,rn)

def post_single(request,post_pk):

    # get post
    post = Post.objects.get(pk=post_pk)

    # return html
    context = {'p':post}
    return render(request, 'papers/post_single.html', context)

def post_context(request,post_pk):

    # get post
    post = Post.objects.get(pk=post_pk)

    # get mother post chain
    posts = get_post_chain(post)

    # insert indents and dedents to post list
    posts =  add_indent_dedent_to_post_list(posts)

    # return html
    context = {'posts':posts,'post':post}
    return render(request, 'papers/post_context.html', context)

def user_notifications(request):
    # get notifications
    user_profile = UserProfile().get_user_profile(request.user)
    posts = list(user_profile.post_reply_notifications.all()) # list is necessary to prevent post_reply_notifications clear from also clearing copy

    # clear notifications
    user_profile.post_reply_notifications.clear()

    # return html
    context = {'navbar':'user_profile','posts':posts, 'number_of_post_reply_notifications':len(posts)}
    return render(request, 'papers/user_notifications.html', context)

def user_library(request):
    user_profile = UserProfile().get_user_profile(request.user)
    citations = user_profile.library.all()
    context = {'navbar':'user_profile','citations':citations}
    return render(request, 'papers/user_library.html', context)

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('papers:frontpage'))

def about_contact(request):
    context = {'navbar':'about'}
    return render(request,'papers/about_contact.html', context)
def about_developers(request):
    context = {'navbar':'about'}
    return render(request,'papers/about_developers.html', context)
def about_jcdb(request):
    context = {'navbar':'about'}
    return render(request,'papers/about_jcdb.html', context)

# user login.  Code from: http://www.tangowithdjango.com/book17/chapters/login.html
def user_login(request): # login is taken up by native django function
    username = request.POST.get('username')
    password = request.POST.get('password')

    # Use Django's machinery to attempt to see if the username/password combination is valid - a User object is returned if it is.
    user = authenticate(username=username, password=password)

    # If we have a User object, the details are correct.
    # If None (Python's way of representing the absence of a value), no user
    # with matching credentials was found.
    if user:
        # Is the account active? It could have been disabled.
        if user.is_active:
            # If the account is valid and active, we can log the user in.
            # We'll send the user back to the homepage.
            login(request, user)
            return HttpResponse("login_successful")
        else:
            # An inactive account was used - no logging in!
            return HttpResponse("banned")
    else:
        # Bad login details were provided. So we can't log the user in.
        return HttpResponse("login_unsuccessful")

# add a citation to user library
def add_citation_to_user_library(request):
    citation_pk = request.POST.get("citation_pk")
    userProfile = UserProfile().get_user_profile(request.user)
    userProfile.library.add(citation_pk)
    userProfile.save()
    return detail(request,citation_pk,0)

# user registration.  Code from: http://www.tangowithdjango.com/book17/chapters/login.html
def register(request):
    # get prospective user data
    username = request.POST.get("username")
    password1 = request.POST.get("password1")
    password2 = request.POST.get("password2")
    email = request.POST.get("email")

    # sanity check on username, password
    username_unique = True
    username_long_enough = True
    username_no_crazy_characters = True
    passwords_match = True
    password_long_enough = True

    if User.objects.filter(username__iexact=username):
        username_unique = False
    if len(username)<6:
        username_long_enough = False
    if not re.match('^[a-zA-Z0-9_-]+$',username):
        username_no_crazy_characters = False
    if password1 != password2:
        passwords_match = False
    if len(password1)<6 or len(password2)<6:
        password_long_enough = False

    if username_unique and username_long_enough and username_no_crazy_characters and passwords_match and password_long_enough:
        user = User.objects.create_user(username, email, password1)
        user.save()
        user = authenticate(username=username, password=password1)
        login(request, user)

    response = {'username_unique':username_unique, 'username_long_enough':username_long_enough,'username_no_crazy_characters':username_no_crazy_characters,'passwords_match':passwords_match,'password_long_enough':password_long_enough}
    return JsonResponse(response)

# landing page
def frontpage(request):
    paperOfTheWeek_citation,dummy = getCitationOfTheWeek()
    context = {'paperOfTheWeek_citation': paperOfTheWeek_citation,'navbar':'home'}
    return render(request, 'papers/frontpage.html', context)

# see all citations in database
def index_deprecated(request):
    citations = Citation.objects.all()

    # Paginate
    paginator = Paginator(citations, 10) # TODO: change this to something more reasonable
    page = request.GET.get('page')
    try:
        citations = paginator.page(page)
        active_page = int(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        citations = paginator.page(1)
        active_page = 1
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        citations = paginator.page(paginator.num_pages)
        active_page = int(paginator.num_pages)

    context = {'citations': citations,'navbar':'index','num_pages':int(paginator.num_pages),'active_page':active_page}
    return render(request, 'papers/index.html', context)

# see all citations in database
def index(request):
    citations = Citation.objects.all()
    context = {'citations': citations,'navbar':'search','show_detail_link':True}
    return render(request, 'papers/index.html', context)

# returns a string, otherwise returns None
def citationSanitizer(request,field_name):
    if request.method == 'POST' and field_name in request.POST:
        f = request.POST[field_name]
        if f is not None and f != '' and f != 'None':
            return f
    return ''

# TODO: check that number of Papers of the Week does not exceed weeks elapsed
def getCitationOfTheWeek():
    t0 = datetime.date(2000, 1, 1)
    today = datetime.date.today()
    days_elapsed = (today-t0).days
    weeks_elapsed = math.floor(days_elapsed / 7)
    num_papersOfTheWeek = len(PaperOfTheWeekInfo.objects.all())
    if num_papersOfTheWeek == 0:
        return 0,0
    else:
        current_index = (weeks_elapsed + PaperOfTheWeek.objects.all()[0].offset) % num_papersOfTheWeek
        citation_pk = PaperOfTheWeekInfo.objects.order_by('order')[current_index].citation.pk
        citation = Citation.objects.get(pk=citation_pk)
        return citation,current_index

# display user profile
def self_user_profile(request):
    context = {'user': request.user, 'navbar':'user_profile'}
    return render(request, 'papers/self_user_profile.html', context)

# display user posts
def user_posts(request, user_pk):
    user = User.objects.get(pk=user_pk)
    posts = Post.objects.filter(creator=user)

journalClubDB/papers/templates/papers/detail.html
{% extends "base.html" %}
{% load templatetags %}

{% block title %}
  {{ citation.get_author_list_truncated }}, {{ citation.get_year_published }}
{% endblock %}

{% block javascript %}
  {% load staticfiles %}
  <script src="{% static 'js/ckeditor/ckeditor.js' %}"></script>
  <link rel="stylesheet" href="{% static 'css/detail.css' %}">
  <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
  <script>
    csrf_js = '{{ csrf_token }}'
    url_upvote = "{% url 'papers:upvote' %}"
    url_downvote = "{% url 'papers:downvote' %}"
  </script>
  <script src="{% static "/static/js/detail.js" %}"></script>
{% endblock %}

{% block body_block %}
  <div class="container">
    <!-- tab bar -->
    <ul class="nav nav-pills nav-justified">
      <li data-threadnumber="0" class="thread-switch-button {% if current_thread == 0 %}active{% endif %}"> <a data-toggle="pill" href="#thread_0">Summary</a></li>
      {% for thread in threads %}
        <li data-threadnumber="{{ forloop.counter }}" class="thread-switch-button  {% if current_thread == forloop.counter %}active{% endif %}"><a data-toggle="pill" href="#thread_{{ forloop.counter }}">{{ thread.title }}</a></li>
      {% endfor %}
      {% if user.is_authenticated %}
        <li data-threadnumber="{{ threads|length|add:1 }}" class="thread-switch-button  {% if current_thread == threads|length|add:1 %}active{% endif %}"><a data-toggle="pill" href="#thread_{{ threads|length|add:1 }}">Personal notes</a></li>
      {% endif %}
    </ul>

    <div class="tab-content">
      <!-- Content for summary jumbotron -->
      <div id="thread_0" {% if current_thread == 0 %} class="tab-pane fade in active" {% else %} class="tab-pane fade" {% endif %}>
        <div class="jumbotron">
          <h1 id="summary-title">{{ citation.title }}</h1>
          <hr >
          <p id="summary-author">{{ citation.get_author_list }}</p>
          <p id="summary-source">{{ citation.get_source | safe }} </p>
          <hr >
          <p id="summary-abstract"> {{ citation.abstract }} </p>

          {% if associated_tags|length != 0 %}
            <hr >
            <p id="summary-tags">Tags:
              {% for associated_tag in associated_tags %}
                <span class="label label-primary">{{ associated_tag }}</span>
              {% endfor %}
            </p>
          {% endif %}

          <!-- superuser functionality to add tags -->
          {% if user.is_superuser %}
            <hr >
            <form id='form-tag' action="{% url 'papers:add_tag' %}" method=POST>
              {% csrf_token %}
              <input type="hidden" name="citation_pk" value="{{ citation.pk }}" />
              <input type="hidden" name="current_thread" value="0" />
              Add tag: <input type="text" name="tag_name"><br>
              <input type="submit" value="Submit">
            </form>
            Possible tags: <br >
            {% for unused_tag in unused_tags %}
              {{ unused_tag }}, &nbsp;
            {% endfor %}
          {% endif %}
          <hr >

          <!-- pubmed link  -->
          <a class="btn btn-primary btn-tiny" href="http://www.ncbi.nlm.nih.gov/pubmed/{{ citation.pubmedID }}" role="button">pubmed link &raquo;</a>

          <!--  add citation to library -->
          {% if user.is_authenticated %}
            {% if citationIsInLibrary == True %}
              <a class="btn btn-primary btn-tiny" href="{% url 'papers:user_library' %}" role="button">This paper is in your personal library</a>
            {% else %}
              <a class="btn btn-primary btn-tiny hyperlink-submit-form" role="button">Add paper to your personal library</a>
              <form action="{% url 'papers:add_citation_to_user_library' %}" method=POST>
                {% csrf_token %}
                <input type="hidden" name="citation_pk" value="{{ citation.pk }}" />
              </form>
            {% endif %}
          {% else %}
            <a data-toggle="modal" data-target="#social-auth-modal" class="btn btn-primary btn-tiny activate-login-modal-library pointer inline" role="button">Add to your library</a>
          {% endif %}

        </div>
      </div>

      <!-- message boards  (ELI5, methodology, etc) -->
      {% for thread,posts,numDepth1Posts in threadsPostsIndents %}
        <div id="thread_{{ forloop.counter }}" {% if current_thread == forloop.counter %} class="tab-pane fade in active" {% else %} class="tab-pane fade" {% endif %}>
          <div class="detail-tab-box">
            <!-- Display number of depth 1 comments, and link for user to submit their own comment -->
              <div class="message-board-number-comments"><h1> {{ numDepth1Posts }} comments
                <sup>
                {% if user.is_authenticated %}
                  <a class='hyperlink-submit-form'>Add your own comment!</a>
                  <form action="{% url 'papers:postForm' %}" method=POST>
                    {% csrf_token %}
                    <input type="hidden" name="citation" value="{{ citation.title }}" />
                    <input type="hidden" name="citation_pk" value="{{ citation.pk }}" />
                    <input type="hidden" name="thread_title" value="{{ thread.title }}" />
                    <input type="hidden" name="thread_description" value="{{ thread.description }}" />
                    <input type="hidden" name="thread_pk" value="{{ thread.pk }}" />
                    <input type="hidden" name="isReplyToPost" value="0" />
                    <input type="hidden" name="mother_pk" value="-1" />
                    <input type="hidden" name="current_thread" value="{{ forloop.counter }}" />
                    <input type="hidden" name="initial_text" value="" />
                    <input type="hidden" name="blockquote" value="False" />
                    <input type="hidden" name="edit_or_reply" value="add" />
                  </form>
                {% else %}
                  <a data-toggle="modal" data-target="#social-auth-modal" class="activate-login-modal-library pointer">Add your own comment!</a>
                {% endif %}
                </sup>
              </div>
             </h2>
             <hr>
            {% include "post_tree_template_condensed.html" %}
          </div> <!-- end  <div class="user_comments"> -->
        </div> <!-- div id="thread_{{ forloop.counter }}" -->
      {% endfor %} <!-- end loop over threadsPostsIndents -->

      <!-- personal notes -->
      {% if user.is_authenticated %}
        <div id="thread_{{ threads|length|add:1 }}" {% if current_thread == threads|length|add:1 %} class="tab-pane fade in active" {% else %} class="tab-pane fade" {% endif %}>
          <div class="detail-tab-box"> <!-- make id unique -->
            <div align="left">
              <br>
              <a class='hyperlink-submit-form'>edit your personal notes</a>
              <form action="{% url 'papers:personalNoteForm' %}" method=POST>
                {% csrf_token %}
                <input type="hidden" name="citation_pk" value="{{ citation.pk }}" />
              </form>
            </div>
            <div>
              {{ personalNote.text|safe }}
            </div>
          </div>
        </div>
      {% endif %}

    </div> <!-- end div tab-content -->
  </div> <!-- end div container -->


{% endblock %}

journalClubDB/papers/templates/papers/register.html
<!DOCTYPE html>
<html>
    <head>
        <title>Rango</title>
    </head>

    <body>
        <h1>Register with Rango</h1>

        {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'papers:index' %}">Return to the homepage.</a><br />
        {% else %}
        Rango says: <strong>register here!</strong><br />

        <form id="user_form" method="post" action="{% url 'papers:register' %}"
                enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
            {{ user_form.as_p }}

            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
        {% endif %}
    </body>
</html>

journalClubDB/papers/templates/papers/search.html
{% extends "base.html" %}
<!-- http://www.alexhadik.com/blog/2014/6/12/create-pubmed-citations-automatically-using-pubmed-api -->

{% load templatetags %} <!-- templatetags cannot be moved to base.html -->


{% block javascript %}
  <!-- custom javascript -->
  {% load staticfiles %}
  <script>
    url_js = "{% url 'papers:addCitation' %}"
    csrf_js = '{{ csrf_token }}'
    url2_js = "{% url 'papers:detail' 0 0 %}"
    url_search = "{% url 'papers:search' 1 %}"
    max_results_per_page = {{ results_per_page }}
  </script>
  <script src="{% static "/static/js/jquery-2.1.4.min.js" %}"></script>
  <script src="{% static "/static/js/xml2json.js" %}"></script> <!-- must be called before search.js -->
  <script src="{% static "/static/js/search.js" %}"></script>
  <script src="{% static "/static/js/citation_summary_template.js" %}"></script>
  <link rel="stylesheet" href="{% static 'css/search.css' %}">
{% endblock %}


{% block body_block %}

  <div class="container">

    <!-- search bar -->
    <div class="row">
      <div id="custom-search-input">
        <div class="input-group col-md-12">
          <div id="custom-search-input">
            <div class="input-group col-md-12">
              <input type="text" class="search-query form-control text-search" placeholder="{{ search_bar_placeholder }}" />
              <span class="input-group-btn">
                <button class="btn btn-danger" type="button">
                  <span class=" glyphicon glyphicon-search"></span>
                </button>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% if citations == "no results" %} <!-- user searched for results but nothing popped up -->
      <br />
      <hr class="grey" />
      <h2 class="color-white">No articles found</h2>
    {% elif citations != "fresh search" %}       <!-- search results -->
      <br />
      <hr class="grey" />
      {% for citation in citations %}
        <br />
        <div class="row">
          {% include "citation_summary_template.html" %}
        </div>
      {% endfor %}
    {% endif %}

    <!-- pagination -->
    <div class="text-center">
      <ul class="pagination">
        {% for i in total_pages|get_range %}
          {% if i|increment == current_page|add:"0" %} <!-- add:"0" to cast string to int -->
            <li class="active"><a>{{ i|increment }}</a></li>
          {% else %}
            <li>
              <a class="page">{{ i|increment }}</a>
              <input type="hidden" name="number" value="{{ i|increment }}" class=".inline" />
            </li>
          {% endif %}
        {% endfor %}
      </ul>
    </div>
  </div>

  <!-- this is a hidden form that holds pubmed xml string  -->
  <form method="POST" id="pubmed-search-form">
    {% csrf_token %}
    <input type="hidden" id="pubmed-search-text" name="json_str" value="{{ search_bar_placeholder }}" />
    <input type="hidden" id="search-bar-placeholder" name="search_bar_placeholder" value="placeholder" />
    <input type="hidden" id="pubmed-search-count" name="count" value="placeholder" />
    <input type="hidden" id="new-page" name="new_page" value="placeholder" />
  </form>


  <!-- this is the loader gif that displays when search is run
       see: http://stackoverflow.com/questions/1964839/how-can-i-create-a-please-wait-loading-animation-using-jquery -->
  <div class="loading-bar-modal"><!-- Place at bottom of page --></div>




{% endblock %}

journalClubDB/papers/templates/papers/search0.html
{% extends "base.html" %}


{% block javascript %}
  <!-- custom javascript -->
  {% load staticfiles %}
  <script src="{% static "/static/js/jquery-2.1.4.min.js" %}"></script>
  <script>
    url_js = "{% url 'papers:addCitation' %}"
    csrf_js = '{{ csrf_token }}'
    url2_js = "{% url 'papers:detail' 0 0 %}"
  </script>
  <script src="{% static "/static/js/search.js" %}"></script>
{% endblock %}

{% block body_block %}

<!-- Search bar -->
<form action="{% url 'papers:search' 1 %}" method=POST>
  {% csrf_token %}
  <input type="text" value="{{ search_str }}" name="search_str">
  <input type="hidden" name="searchInitiated" value="True" />
  <input type="submit">
</form>

{% if freshSearch == False %}
<h1>Search Results</h1>
{% for entry in entries %}
  <li>

    <!-- button to go to detail page, initially hidden-->
    {% if not entry.preexistingEntry %} <!-- Brand new entry that we can import -->
      <a href="dummy_url" id="a_{{ forloop.counter }}"> <!-- dummy_url will get replaced by ajax -->
        <button id="b_{{ forloop.counter }}" style="display:none;">Import</button>
      </a>
    {% else %}  <!-- Entry already exists -->
      <a href="{% url 'papers:detail' entry.preexistingEntry_pk 0 %}" id="a_{{ forloop.counter }}">
        <button id="b_{{ forloop.counter }}">View</button>
      </a>
    {% endif %}

    <!-- button to add pubmed citation to internal database-->
    {% if entry.preexistingEntry %}
    <form method='post' id="f_{{ forloop.counter }}" style="display:none;">
    {% else %}
    <form method='post' id="f_{{ forloop.counter }}">
    {% endif %}
       {% csrf_token %}
       <input type="hidden" id="title_{{ forloop.counter }}" value="{{ entry.title }}"/>
       <input type="hidden" id="author_{{ forloop.counter }}" value="{{ entry.author }}"/>
       <input type="hidden" id="journal_{{ forloop.counter }}" value="{{ entry.journal }}"/>
       <input type="hidden" id="volume_{{ forloop.counter }}" value="{{ entry.volume }}"/>
       <input type="hidden" id="number_{{ forloop.counter }}" value="{{ entry.number }}"/>
       <input type="hidden" id="pages_{{ forloop.counter }}" value="{{ entry.pages }}"/>
       <input type="hidden" id="date_{{ forloop.counter }}" value="{{ entry.date }}"/>
       <input type="hidden" id="fullSource_{{ forloop.counter }}" value="{{ entry.fullSource }}"/>
       <input type="hidden" id="keywords_{{ forloop.counter }}" value="{{ entry.keywords }}"/>
       <input type="hidden" id="abstract_{{ forloop.counter }}" value="{{ entry.abstract }}"/>
       <input type="hidden" id="doi_{{ forloop.counter }}" value="{{ entry.doi }}"/>
       <input type="hidden" id="fullAuthorNames_{{ forloop.counter }}" value="{{ entry.fullAuthorNames }}"/>
       <input type="hidden" id="pubmedID_{{ forloop.counter }}" value="{{ entry.pubmedID }}"/>
       <input type='submit' id="s_{{ forloop.counter }}" value='Import'/>
    </form>

    <!-- title with pubmed link -->
    <p><a href="http://www.ncbi.nlm.nih.gov/pubmed/{{ entry.pubmedID }}">{{ entry.title }}</a></p>
    <!-- author list -->
    <p>
      {% for author in entry.author %}
        {% if forloop.last %}
          and {{ author }}
        {% else %}
          {{ author }},
        {% endif %}
      {% endfor %}
    </p>
    <!-- journal information -->
    <p>{{ entry.fullSource }}</p>
  </li>
{% endfor %}

<!-- Next/Prev page links  -->
{% for page in totalPagesRange %}
  {% if page == pageNumber %}
    {{ page }}
  {% else %}
    <form action="{% url 'papers:search' page %}" method=POST>
        {% csrf_token %}
        <input type="hidden" name="search_str" value="{{ search_str }}" />
        <input type="hidden" name="pageNumber" value="{{ page }}" />
        <input type="hidden" name="totalPages" value="{{ totalPages }}"/>
        <button>{{ page }}</button>
    </form>
  {% endif %}
{% endfor %}
{% endif %}



{% endblock %}

journalClubDB/papers/templates/papers/user_library.html
{% extends "base.html" %}
{% load templatetags %} <!-- templatetags cannot be moved to base.html -->

{% block javascript %}
{% endblock %}

{% block body_block %}

<div class="container">

  <h1 class="color-white">User Library</h1>
  <hr>

  {% for citation in citations %}

    <div class="single_citation">
      {% include "citation_summary_template.html" %}
    </div>
    <br>

  {% endfor %}
</div>



{% endblock %}